"""add P2P columns to ml_features

Revision ID: 26d77a0f50f6
Revises: 7fcb039d2a36
Create Date: 2025-11-19 14:38:58.236103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26d77a0f50f6"
down_revision: Union[str, Sequence[str], None] = "7fcb039d2a36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("_alembic_tmp_budgets")
    with op.batch_alter_table("budgets", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("category_rules", schema=None) as batch_op:
        batch_op.alter_column(
            "enabled",
            existing_type=sa.BOOLEAN(),
            server_default="1",
            existing_nullable=False,
        )

    with op.batch_alter_table("encryption_keys", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_encryption_keys_label"), ["label"], unique=True
        )
        batch_op.drop_column("kms_key_id")
        batch_op.drop_column("wrap_scheme")

    with op.batch_alter_table("encryption_settings", schema=None) as batch_op:
        batch_op.alter_column(
            "write_label",
            existing_type=sa.VARCHAR(length=32),
            server_default=None,
            nullable=True,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            server_default=None,
            nullable=True,
        )

    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.alter_column("txn_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.drop_index(batch_op.f("ix_feedback_created_at"))
        batch_op.create_index(batch_op.f("ix_feedback_label"), ["label"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_feedback_merchant"), ["merchant"], unique=False
        )

    with op.batch_alter_table("help_cache", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("merchant_category_hints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("uq_mch_mc_slug"))

    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("rag_chunks", schema=None) as batch_op:
        # batch_op.add_column(sa.Column('embedding_vec', pgvector.sqlalchemy.Vector(dim=1536), nullable=True))
        batch_op.alter_column(
            "embedding",
            existing_type=sa.BLOB(),
            server_default="",
            existing_nullable=False,
        )
        batch_op.create_index(
            batch_op.f("ix_rag_chunks_doc_id"), ["doc_id"], unique=False
        )

    with op.batch_alter_table("rag_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rag_documents_vendor"), ["vendor"], unique=False
        )

    with op.batch_alter_table("rule_backfill_runs", schema=None) as batch_op:
        batch_op.alter_column(
            "dry_run",
            existing_type=sa.BOOLEAN(),
            server_default="0",
            existing_nullable=False,
        )

    with op.batch_alter_table("rule_suggestion_ignores", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ux_rule_suggestion_ignores_merchant_category"))
        batch_op.create_unique_constraint(
            "ux_rule_suggestion_ignores_merchant_category", ["merchant", "category"]
        )

    with op.batch_alter_table("rule_suggestions", schema=None) as batch_op:
        batch_op.alter_column(
            "last_seen",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("rule_suggestions_persisted", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ux_rule_suggestions_persisted_merchant_category")
        )
        batch_op.create_unique_constraint(
            "ux_rule_suggestions_persisted_merchant_category", ["merchant", "category"]
        )

    with op.batch_alter_table("rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rules_category"), ["category"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_rules_pattern"), ["pattern"], unique=False)

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transactions_category_slug"))
        batch_op.drop_index(batch_op.f("ix_transactions_date_desc"))
        batch_op.drop_index(batch_op.f("ix_txns_deleted_at"))
        batch_op.create_index(
            batch_op.f("ix_transactions_account"), ["account"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_deleted_at"), ["deleted_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_merchant"), ["merchant"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_month"), ["month"], unique=False
        )
        batch_op.create_foreign_key(
            None, "users", ["user_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_column("category_slug")

    with op.batch_alter_table("user_labels", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_labels_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_labels_txn_id"), ["txn_id"], unique=False
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(now())"),
            existing_nullable=False,
        )

    with op.batch_alter_table("user_labels", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_labels_txn_id"))
        batch_op.drop_index(batch_op.f("ix_user_labels_category"))

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("category_slug", sa.VARCHAR(length=64), nullable=True)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_transactions_month"))
        batch_op.drop_index(batch_op.f("ix_transactions_merchant"))
        batch_op.drop_index(batch_op.f("ix_transactions_deleted_at"))
        batch_op.drop_index(batch_op.f("ix_transactions_category"))
        batch_op.drop_index(batch_op.f("ix_transactions_account"))
        batch_op.create_index(
            batch_op.f("ix_txns_deleted_at"), ["deleted_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_date_desc"), ["date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_category_slug"), ["category_slug"], unique=False
        )

    with op.batch_alter_table("rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rules_pattern"))
        batch_op.drop_index(batch_op.f("ix_rules_category"))

    with op.batch_alter_table("rule_suggestions_persisted", schema=None) as batch_op:
        batch_op.drop_constraint(
            "ux_rule_suggestions_persisted_merchant_category", type_="unique"
        )
        batch_op.create_index(
            batch_op.f("ux_rule_suggestions_persisted_merchant_category"),
            ["merchant", "category"],
            unique=1,
        )

    with op.batch_alter_table("rule_suggestions", schema=None) as batch_op:
        batch_op.alter_column(
            "last_seen",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(now())"),
            existing_nullable=False,
        )

    with op.batch_alter_table("rule_suggestion_ignores", schema=None) as batch_op:
        batch_op.drop_constraint(
            "ux_rule_suggestion_ignores_merchant_category", type_="unique"
        )
        batch_op.create_index(
            batch_op.f("ux_rule_suggestion_ignores_merchant_category"),
            ["merchant", "category"],
            unique=1,
        )

    with op.batch_alter_table("rule_backfill_runs", schema=None) as batch_op:
        batch_op.alter_column(
            "dry_run",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("(false)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("rag_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rag_documents_vendor"))

    with op.batch_alter_table("rag_chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rag_chunks_doc_id"))
        batch_op.alter_column(
            "embedding",
            existing_type=sa.BLOB(),
            server_default=sa.text("(x'')"),
            existing_nullable=False,
        )
        batch_op.drop_column("embedding_vec")

    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(now())"),
            existing_nullable=False,
        )

    with op.batch_alter_table("merchant_category_hints", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("uq_mch_mc_slug"),
            ["merchant_canonical", "category_slug"],
            unique=1,
        )

    with op.batch_alter_table("help_cache", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feedback_merchant"))
        batch_op.drop_index(batch_op.f("ix_feedback_label"))
        batch_op.create_index(
            batch_op.f("ix_feedback_created_at"), ["created_at"], unique=False
        )
        batch_op.alter_column("txn_id", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("encryption_settings", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        )
        batch_op.alter_column(
            "write_label",
            existing_type=sa.VARCHAR(length=32),
            server_default=sa.text("'active'"),
            nullable=False,
        )

    with op.batch_alter_table("encryption_keys", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("wrap_scheme", sa.VARCHAR(length=16), nullable=True)
        )
        batch_op.add_column(
            sa.Column("kms_key_id", sa.VARCHAR(length=512), nullable=True)
        )
        batch_op.drop_index(batch_op.f("ix_encryption_keys_label"))

    with op.batch_alter_table("category_rules", schema=None) as batch_op:
        batch_op.alter_column(
            "enabled",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("(true)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("budgets", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(now())"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(now())"),
            existing_nullable=False,
        )

    op.create_table(
        "_alembic_tmp_budgets",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("category", sa.VARCHAR(), nullable=False),
        sa.Column("amount", sa.FLOAT(), nullable=False),
        sa.Column(
            "effective_from",
            sa.DATE(),
            server_default=sa.text("(CURRENT_DATE)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
