"""add rules table

Revision ID: 62bc5ef49a22
Revises: 34dcb7628697
Create Date: 2025-09-04 02:50:37.345019

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62bc5ef49a22"
down_revision: Union[str, Sequence[str], None] = "34dcb7628697"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema (SQLite-safe, idempotent guards)."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    cols = {c["name"] for c in inspector.get_columns("rules")}
    with op.batch_alter_table("rules", schema=None) as b:
        if "merchant" not in cols:
            b.add_column(sa.Column("merchant", sa.String(length=255), nullable=True))
        if "description" not in cols:
            b.add_column(sa.Column("description", sa.Text(), nullable=True))
        if "active" not in cols:
            b.add_column(
                sa.Column("active", sa.Boolean(), server_default="1", nullable=False)
            )
        if "updated_at" not in cols:
            # Use CURRENT_TIMESTAMP for SQLite
            default_expr = (
                sa.text("(CURRENT_TIMESTAMP)")
                if conn.engine.dialect.name == "sqlite"
                else sa.text("now()")
            )
            b.add_column(
                sa.Column(
                    "updated_at",
                    sa.DateTime(timezone=True),
                    server_default=default_expr,
                    nullable=False,
                )
            )
        # Relax pattern/target to nullable if present
        if "pattern" in cols:
            b.alter_column(
                "pattern",
                existing_type=sa.VARCHAR(length=256),
                type_=sa.String(length=255),
                nullable=True,
            )
        if "target" in cols:
            b.alter_column("target", existing_type=sa.VARCHAR(length=32), nullable=True)
    # Create index if missing
    existing_indexes = {ix["name"] for ix in inspector.get_indexes("rules")}
    if "ix_rules_merchant" not in existing_indexes:
        op.create_index(op.f("ix_rules_merchant"), "rules", ["merchant"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rules_merchant"), table_name="rules")
    op.alter_column(
        "rules", "target", existing_type=sa.VARCHAR(length=32), nullable=False
    )
    op.alter_column(
        "rules",
        "pattern",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=256),
        nullable=False,
    )
    op.drop_column("rules", "updated_at")
    op.drop_column("rules", "active")
    op.drop_column("rules", "description")
    op.drop_column("rules", "merchant")
    # ### end Alembic commands ###
