"""add rules table

Revision ID: 62bc5ef49a22
Revises: 34dcb7628697
Create Date: 2025-09-04 02:50:37.345019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62bc5ef49a22'
down_revision: Union[str, Sequence[str], None] = '34dcb7628697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('merchant', sa.String(length=255), nullable=True))
    op.add_column('rules', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('rules', sa.Column('active', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('rules', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('rules', 'pattern',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('rules', 'target',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.create_index(op.f('ix_rules_merchant'), 'rules', ['merchant'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rules_merchant'), table_name='rules')
    op.alter_column('rules', 'target',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('rules', 'pattern',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_column('rules', 'updated_at')
    op.drop_column('rules', 'active')
    op.drop_column('rules', 'description')
    op.drop_column('rules', 'merchant')
    # ### end Alembic commands ###
