"""add P2P features to ml_features table

Revision ID: 7fcb039d2a36
Revises: 207f1bbd265a
Create Date: 2025-11-19 14:33:37.956488

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

try:
    import pgvector.sqlalchemy
except ImportError:
    pgvector = None

# revision identifiers, used by Alembic.
revision: str = "7fcb039d2a36"
down_revision: Union[str, Sequence[str], None] = "207f1bbd265a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("suggestion_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_suggestion_events_txn_id"))

    op.drop_table("suggestion_events")
    with op.batch_alter_table("analytics_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_ae_event"))
        batch_op.drop_index(batch_op.f("idx_ae_server_ts"))

    op.drop_table("analytics_events")
    with op.batch_alter_table("budgets", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("category_rules", schema=None) as batch_op:
        batch_op.alter_column(
            "enabled",
            existing_type=sa.BOOLEAN(),
            server_default="1",
            existing_nullable=False,
        )

    with op.batch_alter_table("encryption_keys", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_encryption_keys_label"), ["label"], unique=True
        )
        batch_op.drop_column("kms_key_id")
        batch_op.drop_column("wrap_scheme")

    with op.batch_alter_table("encryption_settings", schema=None) as batch_op:
        batch_op.alter_column(
            "write_label",
            existing_type=sa.VARCHAR(length=32),
            server_default=None,
            nullable=True,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            server_default=None,
            nullable=True,
        )

    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.alter_column("txn_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.drop_index(batch_op.f("ix_feedback_created_at"))
        batch_op.create_index(batch_op.f("ix_feedback_label"), ["label"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_feedback_merchant"), ["merchant"], unique=False
        )

    with op.batch_alter_table("help_cache", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("merchant_category_hints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("uq_mch_mc_slug"))

    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("rag_chunks", schema=None) as batch_op:
        # Skip pgvector column (requires pgvector extension)
        # batch_op.add_column(sa.Column('embedding_vec', pgvector.sqlalchemy.Vector(dim=1536), nullable=True))
        batch_op.alter_column(
            "embedding",
            existing_type=sa.BLOB(),
            server_default="",
            existing_nullable=False,
        )
        batch_op.create_index(
            batch_op.f("ix_rag_chunks_doc_id"), ["doc_id"], unique=False
        )

    with op.batch_alter_table("rag_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rag_documents_vendor"), ["vendor"], unique=False
        )

    with op.batch_alter_table("rule_backfill_runs", schema=None) as batch_op:
        batch_op.alter_column(
            "dry_run",
            existing_type=sa.BOOLEAN(),
            server_default="0",
            existing_nullable=False,
        )

    with op.batch_alter_table("rule_suggestion_ignores", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ux_rule_suggestion_ignores_merchant_category"))
        batch_op.create_unique_constraint(
            "ux_rule_suggestion_ignores_merchant_category", ["merchant", "category"]
        )

    with op.batch_alter_table("rule_suggestions", schema=None) as batch_op:
        batch_op.alter_column(
            "last_seen",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("rule_suggestions_persisted", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ux_rule_suggestions_persisted_merchant_category")
        )
        batch_op.create_unique_constraint(
            "ux_rule_suggestions_persisted_merchant_category", ["merchant", "category"]
        )

    with op.batch_alter_table("rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rules_category"), ["category"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_rules_pattern"), ["pattern"], unique=False)

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transactions_category_slug"))
        batch_op.drop_index(batch_op.f("ix_transactions_date_desc"))
        batch_op.drop_index(batch_op.f("ix_txns_deleted_at"))
        batch_op.create_index(
            batch_op.f("ix_transactions_account"), ["account"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_deleted_at"), ["deleted_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_merchant"), ["merchant"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_month"), ["month"], unique=False
        )
        batch_op.create_foreign_key(
            None, "users", ["user_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_column("category_slug")

    with op.batch_alter_table("user_labels", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_labels_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_labels_txn_id"), ["txn_id"], unique=False
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(now())"),
            existing_nullable=False,
        )

    with op.batch_alter_table("user_labels", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_labels_txn_id"))
        batch_op.drop_index(batch_op.f("ix_user_labels_category"))

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("category_slug", sa.VARCHAR(length=64), nullable=True)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_transactions_month"))
        batch_op.drop_index(batch_op.f("ix_transactions_merchant"))
        batch_op.drop_index(batch_op.f("ix_transactions_deleted_at"))
        batch_op.drop_index(batch_op.f("ix_transactions_category"))
        batch_op.drop_index(batch_op.f("ix_transactions_account"))
        batch_op.create_index(
            batch_op.f("ix_txns_deleted_at"), ["deleted_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_date_desc"), ["date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_category_slug"), ["category_slug"], unique=False
        )

    with op.batch_alter_table("rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rules_pattern"))
        batch_op.drop_index(batch_op.f("ix_rules_category"))

    with op.batch_alter_table("rule_suggestions_persisted", schema=None) as batch_op:
        batch_op.drop_constraint(
            "ux_rule_suggestions_persisted_merchant_category", type_="unique"
        )
        batch_op.create_index(
            batch_op.f("ux_rule_suggestions_persisted_merchant_category"),
            ["merchant", "category"],
            unique=1,
        )

    with op.batch_alter_table("rule_suggestions", schema=None) as batch_op:
        batch_op.alter_column(
            "last_seen",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(now())"),
            existing_nullable=False,
        )

    with op.batch_alter_table("rule_suggestion_ignores", schema=None) as batch_op:
        batch_op.drop_constraint(
            "ux_rule_suggestion_ignores_merchant_category", type_="unique"
        )
        batch_op.create_index(
            batch_op.f("ux_rule_suggestion_ignores_merchant_category"),
            ["merchant", "category"],
            unique=1,
        )

    with op.batch_alter_table("rule_backfill_runs", schema=None) as batch_op:
        batch_op.alter_column(
            "dry_run",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("(false)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("rag_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rag_documents_vendor"))

    with op.batch_alter_table("rag_chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rag_chunks_doc_id"))
        batch_op.alter_column(
            "embedding",
            existing_type=sa.BLOB(),
            server_default=sa.text("(x'')"),
            existing_nullable=False,
        )
        # Skip pgvector column drop (was never created in SQLite)
        # batch_op.drop_column('embedding_vec')

    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(now())"),
            existing_nullable=False,
        )

    with op.batch_alter_table("merchant_category_hints", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("uq_mch_mc_slug"),
            ["merchant_canonical", "category_slug"],
            unique=1,
        )

    with op.batch_alter_table("help_cache", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feedback_merchant"))
        batch_op.drop_index(batch_op.f("ix_feedback_label"))
        batch_op.create_index(
            batch_op.f("ix_feedback_created_at"), ["created_at"], unique=False
        )
        batch_op.alter_column("txn_id", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("encryption_settings", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        )
        batch_op.alter_column(
            "write_label",
            existing_type=sa.VARCHAR(length=32),
            server_default=sa.text("'active'"),
            nullable=False,
        )

    with op.batch_alter_table("encryption_keys", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("wrap_scheme", sa.VARCHAR(length=16), nullable=True)
        )
        batch_op.add_column(
            sa.Column("kms_key_id", sa.VARCHAR(length=512), nullable=True)
        )
        batch_op.drop_index(batch_op.f("ix_encryption_keys_label"))

    with op.batch_alter_table("category_rules", schema=None) as batch_op:
        batch_op.alter_column(
            "enabled",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("(true)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("budgets", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(now())"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(now())"),
            existing_nullable=False,
        )

    op.create_table(
        "analytics_events",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("event", sa.TEXT(), nullable=False),
        sa.Column(
            "props_json", sqlite.JSON(), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("client_ts", sa.BIGINT(), nullable=True),
        sa.Column("server_ts", sa.BIGINT(), nullable=False),
        sa.Column("rid", sa.TEXT(), nullable=True),
        sa.Column("path", sa.TEXT(), nullable=True),
        sa.Column("ip", sa.VARCHAR(length=64), nullable=True),
        sa.Column("ua", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("analytics_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_ae_server_ts"), ["server_ts"], unique=False
        )
        batch_op.create_index(batch_op.f("idx_ae_event"), ["event"], unique=False)

    op.create_table(
        "suggestion_events",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("txn_id", sa.INTEGER(), nullable=False),
        sa.Column("model_id", sa.VARCHAR(), nullable=True),
        sa.Column("features_hash", sa.VARCHAR(), nullable=True),
        sa.Column("candidates", sqlite.JSON(), nullable=False),
        sa.Column("mode", sa.VARCHAR(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("suggestion_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_suggestion_events_txn_id"), ["txn_id"], unique=False
        )

    # ### end Alembic commands ###
