"""no-op check after standardization

Revision ID: b4068fc306b1
Revises: a81e8444ea56
Create Date: 2025-09-09 17:42:26.785505

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b4068fc306b1"
down_revision: Union[str, Sequence[str], None] = "a81e8444ea56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
