name: ai-finance-agent-oss-clean
services:
  backend:
    build:
      context: C:\ai-finance-agent-oss-clean\apps\backend
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          cpus: 1
          memory: "1572864000"
        reservations:
          cpus: 0.25
          memory: "536870912"
    environment:
      APP_ENV: dev
      CORS_ALLOW_ORIGINS: http://127.0.0.1:5173
      DATABASE_URL: postgresql+psycopg://myuser:4c9248fc7d7d477d919ccc431b1bbd36!PgA1@postgres:5432/finance
      ENCRYPTION_ENABLED: "1"
      GCP_KMS_AAD: app=ledgermind,env=dev
      GCP_KMS_KEY: projects/ledgermind-03445-3l/locations/us-east1/keyRings/ledgermind/cryptoKeys/kek
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/gcp-sa.json
    healthcheck:
      test:
        - CMD-SHELL
        - wget -q -O - http://127.0.0.1:8000/healthz || exit 1
      timeout: 3s
      interval: 10s
      retries: 3
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8000
        published: "8000"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: C:\ai-finance-agent-oss-clean\apps\backend
        target: /app
        bind:
          create_host_path: true
      - type: bind
        source: C:/secrets/ledgermind-backend-sa.json
        target: /secrets/gcp-sa.json
        read_only: true
        bind:
          create_host_path: true
  postgres:
    environment:
      POSTGRES_DB: finance
      POSTGRES_PASSWORD: 4c9248fc7d7d477d919ccc431b1bbd36!PgA1
      POSTGRES_USER: myuser
    image: postgres:15
    networks:
      default: null
    ports:
      - mode: ingress
        target: 5432
        published: "5432"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
        volume: {}
  web:
    build:
      context: C:\ai-finance-agent-oss-clean\apps\web
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_started
        required: true
    environment:
      CI: "true"
      VITE_API_BASE: http://127.0.0.1:8000
    networks:
      default: null
    ports:
      - mode: ingress
        target: 5173
        published: "5173"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: web_node_modules
        target: /app/node_modules
        volume: {}
networks:
  default:
    name: ai-finance-agent-oss-clean_default
volumes:
  pgdata:
    name: ai-finance-agent-oss-clean_pgdata
  web_node_modules:
    name: ai-finance-agent-oss-clean_web_node_modules
