services:
  nginx:
    volumes:
      # Persist SSL certs (Let’s Encrypt) — webroot not needed for DNS-01
      - letsencrypt:/etc/letsencrypt

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: ["tunnel","run"]
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
      - nginx
    healthcheck:
      test: ['CMD', 'cloudflared', 'update', 'check']
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    environment:
      OPENAI_BASE_URL: "http://ollama:11434/v1"
      OPENAI_API_KEY: "ollama"
      MODEL: "gpt-oss:20b"
      DEV_ALLOW_NO_LLM: "0"
      MASTER_KEK_B64: ${MASTER_KEK_B64}
      ENCRYPTION_MASTER_KEY_BASE64: ${ENCRYPTION_MASTER_KEY_BASE64:-${MASTER_KEK_B64}}
      ENCRYPTION_ENABLED: "0"
      CRYPTO_STRICT_STARTUP: "0"
      KMS_PROVIDER: "gcp"
      GCP_KMS_KEY: "projects/ledgermind-03445-3l/locations/us-east1/keyRings/ledgermind/cryptoKeys/kek"
      GCP_KMS_AAD: "app=ledgermind,env=prod"
      GOOGLE_APPLICATION_CREDENTIALS: "/dev/null"
      GRPC_VERBOSITY: "ERROR"
      GRPC_TRACE: ""
    volumes: []
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0) if urllib.request.urlopen('http://127.0.0.1:8000/ready').getcode()==200 else sys.exit(1)"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s
    depends_on:
      ollama:
        condition: service_healthy

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS=/root/.ollama
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "/bin/ollama list >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 30
      start_period: 45s

  ollama-seed:
    image: ollama/ollama:latest
    profiles: ["seed"]
    volumes:
      - ollama-data:/root/.ollama
    entrypoint: ["/bin/sh","-lc"]
    command: |
      set -e
      ollama pull llama3.1:8b    || true
      ollama pull phi3:3.8b      || true
      echo "Seeded models."
    restart: "no"

volumes:
  letsencrypt:
  ollama-data:
