name: CI

on:
  push:
    branches: [ main, develop, UI-fix, Polish-clean-history ]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    name: backend-tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/backend
    env:
      APP_ENV: test
      DEV_ALLOW_NO_LLM: "1"
      DEV_ALLOW_NO_CSRF: "1"
      DATABASE_URL: "sqlite+pysqlite:///:memory:"   # must be quoted
      PYTEST_ADDOPTS: "-q"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            apps/backend/requirements*.txt

      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          else
            pip install -r requirements.txt
          fi

      - name: Lint (ruff) (non-fatal for legacy areas)
        run: |
          if command -v ruff >/dev/null 2>&1; then :; else pip install ruff; fi
          ruff check . || true

      - name: Type check (mypy core) (non-fatal incremental)
        run: |
          if [ -f mypy.ini ]; then
            if command -v mypy >/dev/null 2>&1; then :; else pip install mypy; fi
            mypy . || true
          fi

      - name: Alembic sanity (non-fatal)
        run: python -m alembic current || true

      - name: Run backend tests with coverage
        run: pytest --cov=app --cov-report=xml --cov-report=term

      - name: Upload backend coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: apps/backend/coverage.xml

  web-typecheck-and-tests:
    name: web-typecheck-and-tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: apps/web/pnpm-lock.yaml

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install web deps
        run: pnpm install --frozen-lockfile

      - name: Typecheck (web)
        run: pnpm typecheck

      - name: Test (web)
        run: pnpm test -- --ci --reporter=default
