name: cloudflare-purge-smoke

on:
  push:
    paths:
      - 'scripts/cf-purge.js'
      - '.github/workflows/cloudflare-purge-smoke.yml'
  workflow_dispatch: {}
  schedule:
    - cron: '17 5 * * *'

jobs:
  dry-run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install (minimal)
        run: |
          npm ci --omit=dev || npm install

      - name: Cloudflare purge dry-run (sanity)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: |
          node scripts/cf-purge.js \
            --base=https://app.ledger-mind.org \
            --dist=apps/web/dist \
            --extra=/site.webmanifest,/favicon.ico \
            --dryRun=1
