name: Edge Health

on:
  workflow_dispatch:
  push:
    branches: [ main, prod ]

jobs:
  strict:
    name: Strict Gate (all criticals)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run strict edge verify
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path ops\artifacts -Force | Out-Null
          pwsh ./scripts/edge-verify.ps1 -Json -TunnelStrict -MinHaConnections 1 -CertMinDays 14 `
            | Out-File -FilePath ops\artifacts\edge-verify.json -Encoding utf8
      - name: Fail if any critical present
        shell: pwsh
        run: |
          $j = Get-Content ops/artifacts/edge-verify.json -Raw | ConvertFrom-Json
          if ($null -ne $j.critical -and $j.critical.Count -gt 0) {
            Write-Host "Criticals: $($j.critical -join ', ')"
            exit 2
          }
          Write-Host "Edge health OK (strict)"
      - name: Upload artifact (strict)
        uses: actions/upload-artifact@v4
        with:
          name: edge-verify-strict
          path: ops/artifacts/edge-verify.json

  headers:
    name: Header Integrity Gate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run verifier (header gate)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path ops\artifacts -Force | Out-Null
          pwsh ./scripts/edge-verify.ps1 -Json `
            | Out-File -FilePath ops\artifacts\edge-verify-header.json -Encoding utf8
      - name: Fail on header framing regressions only
        shell: pwsh
        run: |
          $j = Get-Content ops/artifacts/edge-verify-header.json -Raw | ConvertFrom-Json
          $crit = @($j.summary.critical)
          $headerFails = $crit | Where-Object { $_ -in @('healthz_missing_length','healthz_chunked') }
          if ($headerFails.Count -gt 0) {
            Write-Host "Header integrity failed: $($headerFails -join ', ')"
            exit 2
          }
          Write-Host "Header integrity OK"
      - name: Upload artifact (headers)
        uses: actions/upload-artifact@v4
        with:
          name: edge-verify-headers
          path: ops/artifacts/edge-verify-header.json
